BEGIN TRANSACTION;
CREATE TABLE "Audio" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`file_id`	TEXT NOT NULL,
	`category`	TEXT NOT NULL
);
INSERT INTO `Audio` VALUES (1,'BQADAgADBwADKQPzDVYVuh5Y1lWxAg','Прокрастинировать');
INSERT INTO `Audio` VALUES (2,'BQADAgADCAADKQPzDZQphjClLbPBAg','Прокрастинировать');
INSERT INTO `Audio` VALUES (3,'BQADAgADCQADKQPzDVZdZA8Ff6HAAg','Бренно страдать');
COMMIT;
